# Generated by Django 4.0.1 on 2022-02-17 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbox',
            name='password',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='chatbox',
            name='user',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
