# Generated by Django 4.0.1 on 2022-02-17 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_chatbox_password_chatbox_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='', max_length=50, unique=True)),
                ('mood', models.CharField(default='', max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='ChatBox',
        ),
    ]
