# Generated by Django 4.0.1 on 2022-02-20 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_playlist_delete_chatbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='numSongs',
            field=models.IntegerField(default=1),
        ),
    ]
