# Generated by Django 3.2.12 on 2022-04-19 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20220418_2240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='var',
            new_name='temp_var',
        ),
    ]
